---
title: "R Notebook"
output: html_notebook
---

Importing Auto data

```{r}
df = read.table("Auto.data", header = T, na.strings = "?", stringsAsFactors = T)

head(df)
```
deleting the row with missing observations

```{r}
df = na.omit(df)
```


conve cylinder from quantitative to qualitative 
```{r}
df$cylinders = as.factor(df$cylinders)
```


```{r}

summary(df)

```
cylinders,    are qualitative and the rest is quantitative 

------------------
range of quantitative variables 
```{r}
range(df$mpg)

range(df$displacement)

range(df$horsepower)

range(df$weight)

range(df$acceleration)


range(df$year)

range(df$origin)




```
```{r}
mean(df$mpg)

mean(df$displacement)

mean(df$horsepower)

mean(df$weight)

mean(df$acceleration)


mean(df$year)

mean(df$origin)

```
```{r}



sd(df$mpg)

sd(df$displacement)

sd(df$horsepower)

sd(df$weight)

sd(df$acceleration)


sd(df$year)

sd(df$origin)
```









```{r}
View(df[seq(10, 85),])
```



```{r}
newdf = df[-seq(10, 84) , ]
```

```{r}
summary(newdf)
```

```{r}
range(newdf$mpg)

range(newdf$displacement)

range(newdf$horsepower)

range(newdf$weight)

range(newdf$acceleration)


range(newdf$year)

range(newdf$origin)




```
```{r}
mean(newdf$mpg)

mean(newdf$displacement)

mean(newdf$horsepower)

mean(newdf$weight)

mean(newdf$acceleration)


mean(newdf$year)

mean(newdf$origin)

```
```{r}



sd(newdf$mpg)

sd(newdf$displacement)

sd(newdf$horsepower)

sd(newdf$weight)

sd(newdf$acceleration)


sd(newdf$year)

sd(newdf$origin)
```


```{r}
pairs(df)
```
to predict mpg displacement,hoursepower, weight will be good there are a linear relation between them and mpg


















